---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install: gem install bundler -v 2.0.2

script:
  - bundle install
  # disabled cause of: An error occurred while Style/PercentLiteralDelimiters cop
  # - bundle exec rubocop
  - bundle exec rspec